server:
  bind: "127.0.0.1"
  port: 2525
  hostname: "localhost"
  max_connections: 100
  max_connections_per_ip: 100
  max_recipients: 1000
  max_message_size: 10485760 # 10MB
  read_timeout: 30s
  write_timeout: 30s
  email_validation: ["basic"]
  local_domains: ["localhost"]
  virtual_domains: ["localhost.localdomain"]
  relay_domains: []
  spool_dir: "./test-spool"

tls:
  enabled: false

auth:
  plugin_chain: ["memory"]
  plugins:
    memory:
      users:
        - username: "test@localhost"
          password: "test-local-user"
        - username: "test@localhost.localdomain"
          password: "test-virtual-user"

security:
  reverse_dns:
    enabled: false
    reject_on_fail: false
  dnsbl:
    enabled: false
    check_ip: false
    check_sender_domain: false
    providers: []
    action: "log"

logging:
  level: "debug"
  format: "text"

queue:
  buffer_size: 100
  max_consumers: 10

delivery:
  local:
    max_workers: 10
    base_dir_path: "./test-mail/localhost"
  virtual:
    base_dir_path: "./test-mail"
    max_workers: 10