server:
  bind: "127.0.0.1"
  port: 2525
  hostname: "localhost"
  max_connections: 100
  max_connections_per_ip: 10
  max_recipients: 100
  max_message_size: 10485760 # 10MB
  read_timeout: 30s
  write_timeout: 30s
  email_validation: ["basic"]
  local_domains: ["localhost"]
  virtual_domains: ["mail.localhost"]
  relay_domains: []
  spool_dir: "./test-spool"

tls:
  enabled: false

maildir:
  base_path: "./test-mail"

auth:
  plugin_chain: ["memory"]
  plugins:
    memory:
      users:
        - username: "test@localhost"
          password: "test123"

security:
  reverse_dns:
    enabled: false
    reject_on_fail: false
  dnsbl:
    enabled: false
    check_ip: false
    check_sender_domain: false
    providers: []
    action: "log"

logging:
  level: "debug"
  format: "text"

queue:
  buffer_size: 100
  max_consumers: 2