server:
  bind: "127.0.0.1"
  port: 2525
  hostname: "mail.example.com"
  max_connections: 10000
  max_connections_per_ip: 1000
  read_timeout: "30s"
  write_timeout: "30s"

tls:
  enabled: false
  cert_file: "/path/to/cert.pem"
  key_file: "/path/to/key.pem"

maildir:
  base_path: "/var/mail"

auth:
  plugin: "file"
  plugins:
    file:
      users_file: "/etc/golubsmtpd/users"
    memory:
      users:
        - username: "test"
          password: "pass"
        - username: "user@example.com"
          password: "secret123"

security:
  reverse_dns:
    enabled: true
    reject_on_fail: false  # Just log suspicious connections
  dnsbl:
    enabled: true
    check_ip: true
    check_sender_domain: true
    providers:
      - "zen.spamhaus.org"    # Spamhaus combined list
      - "bl.spamcop.net"      # SpamCop
      - "dnsbl.sorbs.net"     # SORBS
    action: "log"             # "log" or "reject"

logging:
  level: "info"
  format: "text"